#!/usr/bin/env bash
# Script: 0-transfer_file
# Transfers a file from client to server using scp

# Check if the number of parameters is less than 3
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# Use scp to transfer the file to the user home directory (~) on the server
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~

# Check if the scp command was successful
if [ $? -eq 0 ]; then
    echo "$file_path transferred successfully to $username@$server_ip:~/"
else
    echo "Error: Failed to transfer $file_path"
fi
