#!/usr/bin/env bash
# This script displays lines containing the word "bash" and extracts the PID of your Bash process.
# Disable shellcheck warning SC2009 for using 'ps' with 'grep'

ps auxf | grep bash
