#!/usr/bin/env bash
# script stops the 4-to_infinity_and_beyond process.

# Specify the process name
process_name="4-to_infinity_and_beyond"

# Find the PID of the process by name
pid=$(ps aux | grep "$process_name" | grep -v "grep" | awk '{print $2}')

if [ -n "$pid" ]; then
    echo "Stopping the $process_name process (PID: $pid)"
    kill "$pid"
else
    echo "The $process_name process is not running."
fi
